apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kube-aws-iam-controller
  name: kube-aws-iam-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kube-aws-iam-controller
  name: kube-aws-iam-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kube-aws-iam-controller
  name: kube-aws-iam-controller
subjects:
  - kind: ServiceAccount
    name: kube-aws-iam-controller
    namespace: operator
roleRef:
  kind: ClusterRole
  name: kube-aws-iam-controller
  apiGroup: rbac.authorization.k8s.io
